# docker-compose.yml example for https://github.com/ServerContainers/samba

services:
  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    restart: always
  web:
    build: .
    context: .
    secrets:
      master_key:
        file: ./rails/config/master.key
    volumes:
      - type: bind
        source: ./railsapp
        target: /railsapp
      - type: volume
        source: gemdata
        target: /usr/local/bundle
      - type: volume
        source: node_modules
        target: /railsapp/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - db
    # note that this network_mode makes it super easy (especially for zeroconf) but is not as safe as exposing ports directly
    # more about that here: https://book.hacktricks.xyz/linux-hardening/privilege-escalation/docker-security/docker-breakout-privilege-escalation#hostnetwork
    #network_mode: host
    # uncomment to solve bug: https://github.com/ServerContainers/samba/issues/50 - wsdd2 only - not needed for samba
    #cap_add:
    #  - CAP_NET_ADMIN
    environment:
      # uncomment to enable fail fast (currently only fails fast if there are conflicts/errors during user/group creation)
      #FAIL_FAST: 1

      
