# fly.toml app configuration file generated for new-rails-memo-app-billowing-lake-1382 on 2024-10-06T23:32:09+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'new-rails-memo-app-billowing-lake-1382'
primary_region = 'nrt'
console_command = '/rails/bin/rails console'

[build]

[deploy]
  release_command = './bin/rails db:prepare'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'
